fail_fast: false
repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: python
        additional_dependencies: [jupyter]
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
      - id: black-jupyter
        name: black-jupyter
        files: \.ipynb$
        language: python
        stages: [commit]
        additional_dependencies: [jupyter-black]
        entry: black